version: '3.7'
services:
  fastdfs-storage1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastdfs-storage1
    network_mode: host
    volumes:
      - ~/docker/data/fastdfs/storage1/conf/storage.conf:/etc/fdfs/storage.conf
      - ~/docker/data/fastdfs/storage1/conf/http.conf:/etc/fdfs/http.conf
      - ~/docker/data/fastdfs/storage1/conf/mime.types:/etc/fdfs/mime.types
      - ~/docker/data/fastdfs/storage1/conf/mod_fastdfs.conf:/etc/fdfs/mod_fastdfs.conf
      - ~/docker/data/fastdfs/storage1/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ~/docker/data/fastdfs/storage1/dfs:/home/dfs
  fastdfs-storage2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastdfs-storage2
    network_mode: host
    volumes:
      - ~/docker/data/fastdfs/storage2/conf/storage.conf:/etc/fdfs/storage.conf
      - ~/docker/data/fastdfs/storage2/conf/http.conf:/etc/fdfs/http.conf
      - ~/docker/data/fastdfs/storage2/conf/mime.types:/etc/fdfs/mime.types
      - ~/docker/data/fastdfs/storage2/conf/mod_fastdfs.conf:/etc/fdfs/mod_fastdfs.conf
      - ~/docker/data/fastdfs/storage2/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ~/docker/data/fastdfs/storage2/dfs:/home/dfs
  fastdfs-storage3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastdfs-storage3
    network_mode: host
    volumes:
      - ~/docker/data/fastdfs/storage3/conf/storage.conf:/etc/fdfs/storage.conf
      - ~/docker/data/fastdfs/storage3/conf/http.conf:/etc/fdfs/http.conf
      - ~/docker/data/fastdfs/storage3/conf/mime.types:/etc/fdfs/mime.types
      - ~/docker/data/fastdfs/storage3/conf/mod_fastdfs.conf:/etc/fdfs/mod_fastdfs.conf
      - ~/docker/data/fastdfs/storage3/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ~/docker/data/fastdfs/storage3/dfs:/home/dfs
  astdfs-storage4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastdfs-storage4
    network_mode: host
    volumes:
      - ~/docker/data/fastdfs/storage4/conf/storage.conf:/etc/fdfs/storage.conf
      - ~/docker/data/fastdfs/storage4/conf/http.conf:/etc/fdfs/http.conf
      - ~/docker/data/fastdfs/storage4/conf/mime.types:/etc/fdfs/mime.types
      - ~/docker/data/fastdfs/storage4/conf/mod_fastdfs.conf:/etc/fdfs/mod_fastdfs.conf
      - ~/docker/data/fastdfs/storage4/conf/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ~/docker/data/fastdfs/storage4/dfs:/home/dfs
